name = "aws-region-nearby"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-04"

[build]
command = "worker-build --release"

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"
