use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct AwsRegion {
    pub name: &'static str,
    pub city: &'static str,
    // pub state: &'static str,
    pub country: &'static str,
    pub country_code: &'static str,
    pub latitude: f64,
    pub longitude: f64,
}

pub const AWS_REGIONS: [AwsRegion; 26] = [
    AwsRegion {
        name: "us-east-1",
        city: "Ashburn",
        // state: "Virginia",
        country: "United States",
        country_code: "US",
        latitude: 38.9445,
        longitude: -77.4558029,
    },
    AwsRegion {
        name: "us-east-2",
        city: "Columbus",
        // state: "Ohio",
        country: "United States",
        country_code: "US",
        latitude: 39.958993960575775,
        longitude: -83.00219086148725,
    },
    AwsRegion {
        name: "us-west-1",
        city: "San Francisco",
        // state: "California",
        country: "United States",
        country_code: "US",
        latitude: 37.61899948120117,
        longitude: -122.375,
    },
    AwsRegion {
        name: "us-west-2",
        city: "Hillsboro",
        // state: "Oregon",
        country: "United States",
        country_code: "US",
        latitude: 45.540394,
        longitude: -122.949825,
    },
    AwsRegion {
        name: "af-south-1",
        city: "Cape Town",
        country: "South Africa",
        country_code: "ZA",
        latitude: -33.9648017883,
        longitude: 18.6016998291,
    },
    AwsRegion {
        name: "ap-east-1",
        city: "Hong Kong",
        country: "China",
        country_code: "HK",
        latitude: 22.308901,
        longitude: 113.915001,
    },
    AwsRegion {
        name: "ap-south-1",
        city: "Mumbai",
        country: "India",
        country_code: "IN",
        latitude: 19.0886993408,
        longitude: 72.8678970337,
    },
    AwsRegion {
        name: "ap-northeast-3",
        city: "Osaka",
        country: "Japan",
        country_code: "JP",
        latitude: 34.42729949951172,
        longitude: 135.24400329589844,
    },
    AwsRegion {
        name: "ap-northeast-2",
        city: "Seoul",
        country: "South Korea",
        country_code: "KR",
        latitude: 37.46910095214844,
        longitude: 126.45099639892578,
    },
    AwsRegion {
        name: "ap-northeast-1",
        city: "Tokyo",
        country: "Japan",
        country_code: "JP",
        latitude: 35.764702,
        longitude: 140.386002,
    },
    AwsRegion {
        name: "ap-southeast-1",
        city: "Singapore",
        country: "Singapore",
        country_code: "SG",
        latitude: 1.35019,
        longitude: 103.994003,
    },
    AwsRegion {
        name: "ap-southeast-2",
        city: "Sydney",
        country: "Australia",
        country_code: "AU",
        latitude: -33.94609832763672,
        longitude: 151.177001953125,
    },
    AwsRegion {
        name: "ap-southeast-3",
        city: "Jakarta",
        country: "Indonesia",
        country_code: "ID",
        latitude: -6.125556,
        longitude: 106.655833,
    },
    AwsRegion {
        name: "ca-central-1",
        city: "Montreal",
        // state: "Quebec",
        country: "Canada",
        country_code: "CA",
        latitude: 45.470556,
        longitude: -73.740833,
    },
    AwsRegion {
        name: "eu-central-1",
        city: "Frankfurt am Main",
        country: "Germany",
        country_code: "DE",
        latitude: 50.033333,
        longitude: 8.570556,
    },
    AwsRegion {
        name: "eu-west-1",
        city: "Dublin",
        country: "Ireland",
        country_code: "IE",
        latitude: 53.421299,
        longitude: -6.27007,
    },
    AwsRegion {
        name: "eu-west-2",
        city: "London",
        country: "England",
        country_code: "GB",
        latitude: 51.4775,
        longitude: -0.461389,
    },
    AwsRegion {
        name: "eu-west-3",
        city: "Paris",
        country: "France",
        country_code: "FR",
        latitude: 49.012798,
        longitude: 2.55,
    },
    AwsRegion {
        name: "eu-south-1",
        city: "Milan",
        country: "Italy",
        country_code: "IT",
        latitude: 45.6306,
        longitude: 8.72811,
    },
    AwsRegion {
        name: "eu-north-1",
        city: "Stockholm",
        country: "Sweden",
        country_code: "SE",
        latitude: 59.651901245117,
        longitude: 17.918600082397,
    },
    AwsRegion {
        name: "me-south-1",
        city: "Manama",
        country: "Bahrain",
        country_code: "BH",
        latitude: 26.27079963684082,
        longitude: 50.63359832763672,
    },
    AwsRegion {
        name: "sa-east-1",
        city: "Sao Paulo",
        country: "Brazil",
        country_code: "BR",
        latitude: -23.435556,
        longitude: -46.473056,
    },
    AwsRegion {
        name: "cn-northwest-1",
        city: "Yinchuan",
        country: "China",
        country_code: "CN",
        latitude: 38.321667,
        longitude: 106.3925,
    },
    AwsRegion {
        name: "cn-north-1",
        city: "Beijing",
        country: "China",
        country_code: "CN",
        latitude: 40.080101013183594,
        longitude: 116.58499908447266,
    },
    AwsRegion {
        name: "us-gov-east-1",
        city: "Ashburn",
        // state: "Virginia",
        country: "United States",
        country_code: "US",
        latitude: 38.9445,
        longitude: -77.4558029,
    },
    AwsRegion {
        name: "us-gov-west-1",
        city: "San Francisco",
        // state: "California",
        country: "United States",
        country_code: "US",
        latitude: 37.61899948120117,
        longitude: -122.375,
    },
];
